name: redux_test
description: A test bed for getting redux working

dependencies:
  flutter:
    sdk: flutter

  redux: 3.0.0
  flutter_redux: 0.5.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
